# Generated by Django 3.0.7 on 2020-06-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Description', models.TextField(default='DataFlair Django tutorials', max_length=254)),
                ('Images', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
